version: '3.4'
services:
    web_ui:
        build: ./web_ui
        restart: always
        ports:
            - 5001:5001
    api:
        build: ./api
        restart: always
        ports:
            - 5000:5000